# Generated by Django 4.2.6 on 2023-10-13 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=222)),
                ('date', models.DateField(default=datetime.datetime(2023, 10, 13, 23, 53, 56, 580103))),
            ],
        ),
    ]
